ALTER TABLE PANIER DROP FOREIGN KEY PANIER_fk0;
ALTER TABLE PANIER CHANGE idClient emailClient varchar(100);
ALTER TABLE PANIER ADD INDEX(emailClient);
ALTER TABLE CLIENT ADD INDEX( email);
ALTER TABLE PANIER ADD FOREIGN KEY (emailClient) REFERENCES CLIENT(email);